Vagrant.configure("2") do |this|
    # Агент перенаправления ssh для клонирования из Github.com
    this.ssh.forward_agent = true

    this.vm.define "web" do |web|
    web.vm.box = "ubuntu/focal64"
        web.vm.hostname = "web"
        # Этот IP используется в сценарии
        web.vm.network "private_network", ip: "192.168.56.10"
        web.vm.network "forwarded_port", guest: 80, host: 8000
        web.vm.network "forwarded_port", guest: 443, host: 8443
        web.vm.provider "virtualbox" do |virtualbox|
            virtualbox.name = "web"
        end
    end

    # this.vm.provision "ansible" do |ansible|
    #     ansible.playbook = "mezzanine.yml"
    #     ansible.verbose = "v"
    #     ansible.compatibility_mode = "2.0"
    #     ansible.host_key_checking = false
    # end
end