---
# vars file for mezzanine
mezzanine_user: "{{ ansible_user }}"
mezzanine_venv_home: "{{ ansible_env.HOME }}/.virtualenvs"
mezzanine_venv_path: "{{ mezzanine_venv_home }}/{{ mezzanine_proj_name }}"
mezzanine_repo_url: "https://github.com/ansiblebook/mezzanine_example.git"
mezzanine_settings_path: "{{ mezzanine_proj_path }}/{{ mezzanine_proj_name }}"
mezzanine_reqs_path: '{{ ansible_env.HOME }}/requirements.txt'
mezzanine_python: "{{ mezzanine_venv_path }}/bin/python"
mezzanine_manage: "{{ mezzanine_python }} {{ mezzanine_proj_path }}/manage.py"
mezzanine_gunicorn_procname: gunicorn_mezzanine
mezzanine_proj_path: "{{ ansible_env.HOME }}/mezzanine/{{ proj_name }}"
mezzanine_proj_name: "{{ proj_app }}"
mezzanine_proj_app: "{{ proj_app }}"
...